import { Poppins } from "next/font/google";
import "./globals.css";
import "tailwindcss/tailwind.css";

import ReduxProvider from "@/Redux/provider/ReduxProvider";

// const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "LeafLink | The Wholesale Cannabis Platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ReduxProvider>
      <html lang='en'>
        <head>
          {/* <link rel="shortcut icon" href={favicon} /> */}
          <link
            rel='icon'
            type='image/png'
            sizes='32x32'
            href='/favicon/favicon-32x32.png'
          />
        </head>
        <body className={poppins.className}>{children}</body>
      </html>
    </ReduxProvider>
  );
}
