
import { Poppins } from 'next/font/google'
import './globals.css'

// const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({
  weight: ['400', "500", '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        {children}
      </body>
    </html>
  )
}
